### ISSUE TITLE
[sync_kernel_to_website][register_documents_task] Erro na atribuição de campo order de documento

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#230]
### Descrição do problema
Durante a execução da task `register_documents_task` da DAG `sync_kernel_to_website`, ocorreu o seguinte erro, que provocou a interrupção da tarefa:

```
[2020-10-15 21:48:40,173] {taskinstance.py:1047} ERROR - invalid literal for int() with base 10: 'E1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/sync_kernel_to_website.py", line 685, in register_documents
    documents_to_get, _get_relation_data, fetch_documents_front, ArticleFactory
  File "/usr/local/airflow/dags/operations/sync_kernel_to_website_operations.py", line 307, in try_register_documents
    document_xml_url,
  File "/usr/local/airflow/dags/operations/sync_kernel_to_website_operations.py", line 246, in ArticleFactory
    article.order = int(document_order)
ValueError: invalid literal for int() with base 10: 'E1'
```
O documento que estava sendo sincronizado era o de PID v3 `rNcN3bY9tvWfXFxdcFQxhRx`, que tem esse dado no `fpage`, que aceita dado alfanumérico, segunda a SPS [1].

A tarefa tenta converter o dado para `int` e atribuir como campo `order` em instância de `Article` do OPAC-Schema e o erro acontece.

### Passos para reproduzir o problema
1. Registre no Kernel um documento que tenha fpage com um dado alfanumérico.
2. Execute a DAG `sync_kernel_to_website` para que o documento registrado seja sincronizados para o site.
3. A tarefa `register_documents_task` deve lançar o erro citado e falhar a execução.

### Comportamento esperado
A exceção acima não deveria ocorrer e o artigo deveria ser publicado no site sem este problemas.

### Screenshots ou vídeos
.

### Anexos
[1] - https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-fpage.html

### Ambiente utilizado
O erro foi identificado no OPAC-Airflow rodando no ambiente de produção do SPF.

**Comment by robertatakenaka** [comment]
@patymori qual é o motivo de ter que converter par `int`?

**Comment by patymori** [comment]
> @patymori qual é o motivo de ter que converter par `int`?

Puxando da memória, eu não saberia dizer exatamente o que levou o uso do `int` nesta parte do código. Com sorte quem colocou descreveu no commit. É possível tentar resgatar essa informação buscando no repositório.

**Comment by patymori** [comment]
> > @patymori qual é o motivo de ter que converter par `int`?
> 
> O atributo `order` de `Article` no OPAC-Schema é um `int`, então a primeira razão seria esta. O que talvez não fosse esperado quando este código foi desenvolvido é que este campo pudesse não ser numérico.
